include classpath("application.conf")

queues {
  notification-queue {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
  ingestion-queue {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
